### PR TITLE
Curate `sct-pipeline / gm-challenge-data`

### PR DESCRIPTION
**Pull request by alexfoias**
Fixes https://github.com/sct-pipeline/gm-challenge-data/issues/1

### CODE REVIEW

**Comment by alexfoias** [comment]
@jcohenadad The current version puts the files in this order:
~~~
├── derivatives
│   └── labels
│       └── sub-10062
│           └── anat
│               ├── sub-10062_acq_list.txt
│               ├── sub-10062_acq_params.pdf
│               ├── sub-10062_run-1_T2starw_gmseg-manual.json
│               ├── sub-10062_run-1_T2starw_gmseg-manual.json
│               ├── sub-10062_run-1_T2starw_seg-manual.json
│               └── sub-10062_run-1_T2starw_seg-manual.json
│
└── sub-10062
    └── anat
        ├── sub-10062_run-1_T2starw.json
        ├── sub-10062_run-1_T2starw.nii.gz
        ├── sub-10062_run-2_T2starw.json
        └── sub-10062_run-2_T2starw.nii.gz
~~~

Unless you want to put the `*.txt` and `*.pdf` on the root of subject and not in derivatives.

**Comment by alexfoias** [comment]
@jcohenadad Please let me know if I can push this structure, or if we need to tweak something.

**Comment by jcohenadad** [comment]
> @jcohenadad The current version puts the files in this order:

it would be helpful if you could indicate what is the difference with what i proposed?

**Comment by alexfoias** [comment]
The main difference from [this](https://github.com/sct-pipeline/gm-challenge-data/issues/1#issue-945409003) is `sub-XXX_acq_list.tx`t and `sub-XXX_acq_params.pdf` hosted under `/derivatives/labels/sub-XXX/anat`

**Comment by jcohenadad** [comment]
> The main difference from [this](https://github.com/sct-pipeline/gm-challenge-data/issues/1#issue-945409003) is `sub-XXX_acq_list.tx`t and `sub-XXX_acq_params.pdf` hosted under `/derivatives/labels/sub-XXX/anat`

ok that's good!

**Comment by alexfoias** [comment]
sure.

**Comment by alexfoias** [comment]
@jcohenadad Can I merge this one since https://github.com/sct-pipeline/gm-challenge-data/pull/2 was closed ?

**Pull request merged**
