### PR TITLE
`GmSegChallenge2016` dataset BIDSification

### PR DESCRIPTION
**Pull request by valosekj**
This PR discusses the BIDSification of `GmSegChallenge2016` dataset.

Input datasets (training and testing) and the BIDSified dataset are located in `~/extrassd1/janvalosek/GmSegChallenge2016`.

Related to https://github.com/neuropoly/data-management/issues/195

## Input dataset structure

- training dataset - 10 subjects from each site (10 x 4 = 40 subjects). Each subject has:
   * `image.nii.gz` representing `T2star.nii.gz` image
   * four `mask-r` files with manual labels of WM (pixel value 2) and GM (pixel value 1)
   *  `levels.txt` file
- testing dataset - 10 subjects from each site (10 x 4 = 40 subjects). Each subject has: 
   * `image.nii.gz` representing `T2star.nii.gz` image
   *  `levels.txt` file

```console
├── training-data-gm-sc-challenge-ismrm16-v20160302b
│   ├── license.txt
│   ├── site1-sc01-image.nii.gz
│   ├── site1-sc01-levels.txt
│   ├── site1-sc01-mask-r1.nii.gz
│   ├── site1-sc01-mask-r2.nii.gz
│   ├── site1-sc01-mask-r3.nii.gz
│   ├── site1-sc01-mask-r4.nii.gz
│   ├── ...
└── test-data-gm-sc-challenge-ismrm16-v20160401
    ├── license.txt
    ├── site1-sc11-image.nii.gz
    ├── site1-sc11-levels.txt
    ├── ...

```

## Output dataset structure

```console
├── code
│   └── curate_gmsegchallenge2016.py
├── dataset_description.json
├── derivatives
│   ├── dataset_description.json
│   └── manual_labels
│       ├── sub-epm001
│       │   └── anat
│       │       ├── sub-epm001_T2star_label-vertebral-levels.txt
│       │       ├── sub-epm001_T2star_label-GM_mask1.json
│       │       ├── sub-epm001_T2star_label-GM_mask1.nii.gz
│       │       ├── sub-epm001_T2star_label-GM_mask2.json
│       │       ├── sub-epm001_T2star_label-GM_mask2.nii.gz
...
│       │       ├── sub-epm001_T2star_label-SC_mask1.json
│       │       ├── sub-epm001_T2star_label-SC_mask1.nii.gz
...
│       │       ├── sub-epm001_T2star_label-WM_mask1.json
│       │       ├── sub-epm001_T2star_label-WM_mask1.nii.gz
...
├── LICENSE
├── participants.json
├── participants.tsv
├── sub-epm001
│   └── anat
│       ├── sub-epm001_T2star.json
│       └── sub-epm001_T2star.nii.gz
├── sub-epm002
│   └── anat
│       ├── sub-epm002_T2star.json
│       └── sub-epm002_T2star.nii.gz
...
```

### SC, WM and GM segmentations

I re-created SC, WM and GM segmentations from the input manual labels contacting both WM (pixel value 2) and GM (pixel value 1) segmentations using `sct_maths`. Also, I created json sidecars for each segmentation containing the rater's name.

SCseg (`-bin 0`):

https://github.com/neuropoly/data-management/blob/5c99d230a1bf87eb2587be8732f0b2fe27799c74/scripts/curate_gmsegchallenge2016.py#L144-L150

GMseg (`-uthr 1`):

https://github.com/neuropoly/data-management/blob/5c99d230a1bf87eb2587be8732f0b2fe27799c74/scripts/curate_gmsegchallenge2016.py#L170-L176

WMseg (`-bin 1`):

https://github.com/neuropoly/data-management/blob/5c99d230a1bf87eb2587be8732f0b2fe27799c74/scripts/curate_gmsegchallenge2016.py#L118-L124

### Manual raters

Based on [GM mask delineation](https://www.sciencedirect.com/science/article/pii/S1053811917302185#s0025) section from Prados et al., 2017:

```
Rater 1 (MY) and rater 3 (GD), ...
Rater 2 (SMD) and 4 (BL) ...
```

I included the following rater's names in the json sidecars:
https://github.com/neuropoly/data-management/blob/5c99d230a1bf87eb2587be8732f0b2fe27799c74/scripts/curate_gmsegchallenge2016.py#L62-L67

### Additional files

`dataset_description.json`, `participants.json`, `participants.tsv`, and `README` are attached to this PR to allow easy feedback. @jcohenadad could you please add the contact person and email conversion to the README?
`LICENSE` is a copy of the [licence from the input dataset](https://www.dropbox.com/s/8hwqy0u6a1a6z7x/training-data-gm-sc-challenge-ismrm16-v20160302b.zip?dl=0&file_subpath=%2Flicense.txt).

UPDATE 2023-01-03: The `*-levels.txt` files containing information about the vertebral levels were copied to `derivatives/manual_labels`. To be clear that these txt files contain info about vertebral levels and not about discs, I choose the following filename: `*_T2star_label-vertebral-levels.txt`, for example: `sub-epm001_T2star_label-vertebral-levels.txt`.

### CODE REVIEW

**Comment by jcohenadad** [comment]
> I have been considering the creation of vertebral levels nii files using sct_label_vertebrae or sct_labels_utils.

I'm not sure these data will be used to train DL model for disc labeling because the discs are poorly visible on these axial GRE data. So maybe it's ok to keep the disc labels as is.

**Comment by jcohenadad** [comment]
@valosekj the PR is still in 'draft' mode but you requested a review from me. Is it ready for review?

**Comment by valosekj** [comment]
> I'm not sure these data will be used to train DL model for disc labeling because the discs are poorly visible on these axial GRE data. So maybe it's ok to keep the disc labels as is.

Okay. I kept the labeling as txt files and placed them under `derivatives/manual_labels/xxx/anat/`:

```
├── derivatives
│   └── manual_labels
│       ├── sub-epm001
│       │   └── anat
│       │       ├── sub-epm001_T2star_label-vertebral-levels.txt
│       │       ├── sub-epm001_T2star_label-GM_mask1.json
│       │       ├── sub-epm001_T2star_label-GM_mask1.nii.gz
...
```

To be clear that these txt files contain info about vertebral levels and not about discs, I choose the following filename: `*_T2star_label-vertebral-levels.txt`.

**Comment by valosekj** [comment]
> @valosekj the PR is still in 'draft' mode but you requested a review from me. Is it ready for review?

Sorry about that. 
Based on https://github.com/neuropoly/data-management/issues/195#issuecomment-1369202235, I renamed `derivatives/labels` to `derivatives/manual_labels` and got rid of the `desc-manual`.
Now, the PR is ready for review.

**Review by jcohenadad — APPROVED** [review]
I haven't tested the script to generate the separate labels but overall it looks good! thank you @valosekj 🙏

**Comment by valosekj** [comment]
> I haven't tested the script to generate the separate labels but overall it looks good! thank you @valosekj 🙏

Okay! Thank you. I will [upload the dataset to git-annex](https://intranet.neuro.polymtl.ca/data/git-datasets.html#new-repository). Then I will close this PR without merging and delete the branch. 

Regarding the [README](https://github.com/neuropoly/data-management/blob/jv/curate_gmsegchallenge2016/scripts/README.md); can I add Ferran Prados as a contact person?

**Comment by jcohenadad** [comment]
> Regarding the [README](https://github.com/neuropoly/data-management/blob/jv/curate_gmsegchallenge2016/scripts/README.md); can I add Ferran Prados as a contact person?

👍

**Comment by valosekj** [comment]
The dataset uploaded to git-annex --> closing this PR.

**Pull request closed without merging**
